#!/bin/bash
NAME=collaborabm
TARGET=$HOME/$NAME
GIT_DIR=$HOME/$NAME.git
BRANCH=main

while read oldrev newrev ref
do
 # only checking out the main
 if [ "$ref" = "refs/heads/$BRANCH" ];
 then
  echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
  git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
  cd $TARGET/doc/bookdown
  rm _main.Rmd
  Rscript -e 'bookdown::render_book("index.Rmd",output_dir="/var/www/html/collaborabm")'
  exit $?
 else
 # perform more tasks like migrate and run test, the output of these commands will be shown on the push screen
  echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server. We could here push the gh-pages branch to a gthub public repo"
 fi
done
