# A chapter on demograpy

Because people have childs who have childs...

$$ 1+1=2 $$

Check with Latex
```{r universaltruth}
1+1==2
```

small tests


$$ y_i = \frac{K}{1 + \left(\frac{K - y_{i-1}}{y_{i-1}}\right)*e^{-r}} $$

A more realistic growth: the environment modulate a carrying capacity K

```{r popgrowth}

K=1000+faketemp*sample(100:200,size=tstep,replace=T)
N=50
pop=rep(0,tstep)
pop[1]=N
r=environment(tstep,omega=4,delta=.1)+.2
for(i in 2:tstep)
    pop[i]=K[i]/(1 + (( K[i] - pop[i-1])/pop[i-1])*exp(-r[i]))
```

```{r visupopgrowth,fig.cap="logistic growth and correlated data",out.width="100%",fig.height=4,fig.width=9,fig.show="hold"}

    layout(matrix(1:4,nrow=4,ncol=1),heights=c(.2,.2,.2,.4))
    par(mar=c(0,4,1,1))
    plot(1:tstep,faketemp,xlab="time",ylab="Environment",main="",type="l",xaxt="n",frame.plot=F,col="blue")
    plot(1:tstep,K,xlab="time",ylab="Carrying Capacity",main="",type="l",xaxt="n",frame.plot=F,col="green")
    plot(1:tstep,r,xlab="time",ylab="rate of growth",main="",type="l",xaxt="n",frame.plot=F,col="red")
    par(mar=c(4,4,1,1))
    plot(1:tstep,pop,xlab="time",ylab="popsize",main="",type="l",lwd=1.5,frame.plot=F)
```

