# Populatin grow on multiple sites

```{r}
#' @param pt a vector point around witch decvay is computed
#' @param rast a raster to compute distances
#' @param L sstarting point of decay
logisticdecay <- function(pt,rast,L=1,k=0.0001,x0=60000){
    ds=distance(rast,pt)
    (L-L/(1+exp(-k*(ds-x0))))
}

#' @param n number of individuals
#' @param ages initial ages
#' @param p_sex proportion of the different sex
#' return a dataframe with age and sex of every individual of the population
initpopstruc <- function(n=100,ages=10:30,p_sex=c(0.5,0.5)) data.frame("Age" = sample(ages,n,ages, replace = TRUE), "Sex" = sample(c("M","F"), n, prob = p_sex, replace = TRUE))   

#' @param list_sites a list of population for all initial sites of the simulation
#' @param ts length of simulation
initlistsites <- function(list_sites,ts=200){
    Nts=matrix(0,nrow=ts+1,ncol=length(list_sites))
    Nts[1,]=sapply(list_sites,nrow)
    Nts
}


#' @param Kbase baseline carrying capacity or different culturesj
#' @param sites raster with site and culture
#' @param ressources a raster type for fall sites
initKs <- function(Kbase=c("HG"=30,"F"=120),sites,ressources){
    Ks=round(Kbase[sites$culture]+rnorm(length(sites),0,10))
    while(any(Ks<1)) Ks=round(Kbase[sites$culture]+rnorm(length(sites),0,10))
    #Ks[sites$culture=="F"]=Ks[sites$culture=="F"]*runif(sum(sites$culture=="F"),1,1)
    Ks=Ks*(1+extract(ressources,sites)[,2])
    Ks
}


```


## Environmental resources
We generate zone of hight resource, that will attract settlements and support higher K

```{r}

##ressource geolocalisation set manually
goodressources=vect(
                    cbind(
                     x=c(-0.2300711,-3.1455282,-0.5086485,-1.9639755,-0.4077843,0.019688,-3.116710),
                     y=c(3.6423000,-0.2551019,-0.7440748,1.1303214,1.0248567,0.2194895,2.0267718)
                     )
                    )
#spread of ressources
areas=4*c(100,2000,200,300,100,200,400)
#speed of ressource decay:
ks=c(0.0002,0.0001000,0.0001600,0.0001800,0.00040,.0002,0.0002)/4

crs(goodressources)=crs(height.ras)

allres=lapply(seq_along(goodressources),function(i)logisticdecay(goodressources[i],mask(height.ras,viable),x=areas[i],k=ks[i]))

ress=allres[[1]]
for(i in 2:length(allres))
    ress=ress+allres[[i]]
ress=mask(ress,viable)
plot(ress)
```
## Initial sites and size:

```{r,eval=F}

#initialisation

ts=800
Kbase=c("HG"=30,"F"=120) #difference in K for the two cultures
minimals=c("HG"=.14,"F"=.19) #how big the group of migrant should be to create a new city vs migrate to a existisng one 
cul_ext=c("HG"=10,"F"=2) #spatial penality to extent: lower, bigger penality
penal_cul=c("HG"=3,"F"=2.2) #penality of occupational area: low, other sites can cam close
prob_birth=c("HG"=0.3,"F"=0.35)
prob_survive=c("HG"=0.8,"F"=0.4)
prob_split=c("HG"=0.7,"F"=0.44)


cultures=rep("HG",length(sites))

cultures[(crds(sites)[,"x"] < -1 & crds(sites)[,"y"] < 1)]="F"
sites$culture=as.factor(cultures)

sites$Ks=initKs(Kbase,sites,ress)

sites=vect(readRDS("testsites.RDS"))
Ks=sites$Ks
cultures=sites$culture
INs=round(runif(length(sites),.85,.95)*sites$Ks) #Population size at initialisation


Ips <- lapply(INs,initpopstruc ) #initialise population structure for all sites

Nts=initlistsites(Ips,ts=ts)

```


Use ressource to adjust the Ks:
```{r,eval=F}
plot(sites,cex=(1+Nts[1,]/100),pch=21,bg=rainbow(2,alpha=.6)[as.factor(sites$culture)])
```


We will run the simulation step by stepk
Step by step to allow interaction between sites:

```{r,eval=F}
## Run stochastic process  

### visualisation =====
frame=0
foldervid="mapgrowth"
plot(height.ras^1.9,col=col_ramp(50),legend=F,reset=F)
plot(height.wat,col="lightblue",add=T,legend=F)
plot(sites,cex=(1+Nts[1,]/100),pch=21,add=T,bg=rainbow(2,alpha=.6)[as.factor(cultures)])
plot(ress,add=T,alpha=.2,col=colorRampPalette(c("white","yellow","orange","red"))(80))
###


for (i in 2:(ts+1)){
    print(paste("decades",i))
if(visumin){
        ### visualisation =====
        frame=frame+1
        filename=sprintf("map_%08d.png", frame)
        png(file.path(foldervid,filename),width=800,height=800,pointsize=20)
        plot(height.ras^1.9,col=col_ramp(50),legend=F,reset=F,main=paste0("year ",i) )
        plot(height.wat,col="lightblue",add=T,legend=F)
        ########
}

    for(s in sample(seq_along(sites))){

if(visu){
        ### visualisation =====
        frame=frame+1
        filename=sprintf("map_%08d.png", frame)
        png(file.path(foldervid,filename),width=800,height=800,pointsize=20)
        plot(height.ras^1.9,col=col_ramp(50),legend=F,reset=F,main=paste0("year ",i) )
        plot(height.wat,col="lightblue",add=T,legend=F)
        ########
}

        city=NULL
        Ips[[s]] <- Gpd(Ips[[s]], K = Ks[[s]], P_o=prob_birth[sites$culture[s]],prob = prob_survive[sites$culture[s]] ) #compute new population for the sites
        newN=nrow(Ips[[s]]) #count population size


        if(newN>=(Ks[[s]])){ #if new population is more than carrying capacity: migration scenario
            migrants=newN-round(Ks[[s]]*0.9)
            ##Creation of new city
            new_site=NULL
            #if(sites$culture[s]=="F")print(paste("possib",migrants, (minimals[sites$culture[s]]*sites$Ks[s])))
            tmp=Nts[i-1,]
            tmp[Nts[i,]>0]=Nts[i,Nts[i,]>0]
            #tmp=tmp+sqrt(sites$Ks)
            buffersize=(sqrt(tmp)+penal_cul[cultures])*3000*runif(1,.95,1.25)
            buffersize[tmp==0]=0

            if(migrants>= (minimals[sites$culture[s]]*sites$Ks[s]) & runif(1)<prob_split[sites$culture[s]] ){ #if supropulation > 10 people, 10% chance of creation of a new city

                print(paste("look for new spot for ",migrants, "from site",s,"culture",sites$culture[s]))
                territory=erase(viable,buffer(sites,buffersize))

                if(length(territory)>0){
                    print(paste("found new spot",migrants))

                    ##select a new site given its distance to the old one and the ressource available in ress
                    d2=logisticdecay(sites[s],height.ras,x=20000*cul_ext[sites$culture[s]])
                    w=(.7*d2+.3*ress)/(.7*minmax(d2)[2] + .3*minmax(ress)[2])
                    new_site=spatSample(x=mask(w*logisticdecay(sites[s],height.ras,k=0.00002,x=20000*cul_ext[sites$culture[s]]),territory),size=1,method="weights",xy=T)[1:2]
                    new_site=vect(new_site,geom=c("x","y"))

                    if(length(new_site)>0 & all(!is.na(crds(new_site)))){
                        ##add new site to site listes
                        ##initialise population struc of new site
                        Ips[[length(Ips)+1]]= initpopstruc(n=migrants)
                        new_site$culture=sites$culture[s]
                        new_site$Ks=initKs(Kbase,sites=new_site,ress)

                        sites=rbind(sites,new_site)

                        Ks[length(Ks)+1]=new_site$Ks
                        city=(length(Ks))
                        Nts=cbind(Nts,rep(0,ts+1))
                        cultures=c(cultures,cultures[s])
                        print("ii")
                    }
                }
            }
            ## if no creation of new city happen, there is 90% chance that people will move
            if(length(new_site)==0 && runif(1)>.1 ){

                #getj
                att=extract(ress,sites)[,2]
                space=sites$Ks-(Nts[i-1,]+migrants)
                dis=extract(logisticdecay(sites[s],height.ras,k=0.00002,x=1),sites)[,2]
                attractivity=att*space*dis
                attractivity=attractivity*(1+3*(sites$culture[s]==sites$culture)) #4 times more likely to go to similar culture
                attractivity[s]=min(attractivity)-1
                attractivity=exp(attractivity)/sum(exp(attractivity))
                city=sample(size=1,x=seq_along(sites),prob=attractivity)
            }
            Nts[i,city]=Nts[i-1,city]+migrants
            newN=newN-migrants
        }
        Nts[i,s]=newN

if(visu){
        ###visualisation=========
        sitescols=rep(1,length(sites))
        siteslwd=rep(1,length(sites))
        ii=NULL
        if(!is.null(city)){
            sitescols[s]="yellow"
            sitescols[city]="red"
            siteslwd[s]=3
            siteslwd[city]=3
            ii=st_cast(st_combine(st_as_sf(sites[c(s,city)])),"LINESTRING")
        }
        if(!is.null(ii))plot(ii,add=T)
        tmp=Nts[i-1,]
        tmp[Nts[i,]>0]=Nts[i,Nts[i,]>0]
        plot(sites,cex=(1+tmp/100),pch=21,add=T,bg=rainbow(2,alpha=.6)[as.factor(sites$culture)],lwd=siteslwd,col=sitescols)
        dev.off()
        ###=======================
}
    }
if(visumin){
        plot(sites,cex=(as.integer(Nts[i,]>0)+Nts[i,]/100),pch=21,add=T,bg=rainbow(2,alpha=.6)[as.factor(sites$culture)])
        dev.off()
}
#par(mfrow=c(2,1))
#plot(1,1,type="n",xlim=c(0,i),ylim=c(0,max(Nts)),xlab="time",ylab="popsize")
#lapply(1:ncol(Nts),function(j)lines(Nts[,j],col=rainbow(2)[as.factor(sites$culture)[j]]))
#plot(apply(Nts,1,sum),xlab="time",ylab="popsize")
}
```

Visualise:
Record deposit and  loss
```{r,fig.width="25%"}
alldeposit=lapply(1:ncol(Nts),function(i)Rec_c(sapply(Nts[,i],A_rates), InitBP = 7500,ts=ts,r = 0.2, Max_bone_thickness = "m"))
maxy=max(sapply(alldeposit,function(i)max(apply(i,2,sum))))

lapply(alldeposit,function(depo)barplot(t(depo),col=viridis(ts+1),ylim=c(0,maxy)))
```


```{r,eval=F}
par(mfrow=c(2,1))
plot(1,1,type="n",xlim=c(0,ts),ylim=c(0,max(Nts)),xlab="time",ylab="popsize")
lapply(1:ncol(Nts),function(i)lines(Nts[,i],col=rainbow(2)[as.factor(sites$culture)[i]]))
plot(apply(Nts,1,sum),xlab="time",ylab="popsize")




new_site=vect(as.data.frame(locator()),geom=c("x","y"))
crs(new_site)=crs(height.ras)
d2=logisticdecay(new_site,height.ras,x=20000)

plot(d2)
w=(.7*d2+.3*ress)/(.7*minmax(d2)[2] + .3*minmax(ress)[2])
plot(w)
plot(mask(w*logisticdecay(new_site,height.ras,k=0.00002,x=1),territory))
multisamp=sapply(1:1000,function(i)spatSample(x=w,size=1,method="weights",xy=T)[1:2])


```



