## Function 14. Initial carrying capacity
#' @title Initialize carrying capacity
#' @description
#' It generates a random carrying capacity for each site, but based on the amount
#' of resources.
#' 
#' @param Kbase baseline carrying capacity or different cultures
#' @param sites raster with site and culture
#' @param ressources a raster type for fall sites
#' @param sizeexp Cultures for which to apply a random number generated by an exponential
#' distribution that multiplies the amount of resources
#' @param rate Rate of exponential distribution
#' @export
#' @return A list with a carrying capacity for each culture
initKs <- function(Kbase=c("HG"=30,"F"=120), sites, ressources,
                   sizeexp=NULL, rate=.5){
  Ks <- round(Kbase[sites$culture] + rnorm(length(sites), 0, 10))
  while(any(Ks<1)){
    Ks <- round( Kbase[sites$culture] + rnorm(length(sites), 0, 10) )
  }
  #Ks[sites$culture=="F"]=Ks[sites$culture=="F"]*runif(sum(sites$culture=="F"),1,1)
  tmp <- Ks * (1 + extract(ressources, sites)[, 2])
  if(!is.null(sizeexp)){
    tmp[sites$culture==sizeexp] <- (
      (Ks[sites$culture==sizeexp]) *
        (1 + rexp(sum(sites$culture==sizeexp), rate=rate) * extract(ressources, sites[sites$culture==sizeexp])[,2])
    )
  }
  tmp
}


 
## Function 15. Create population matrix
#' @title Create initial population matrix
#' @description
#' This functions initializes a population matrix
#' @param n number of individuals
#' @param ages initial ages
#' @param p_sex proportion individuals of different sex
#'
#' @return a dataframe with age and sex of every individual of the population
#' @export
initpopstruc <- function(n=100, ages=10:30, p_sex=c(0.5, 0.5)){
  initpop = data.frame(
    "Age" = sample(ages, n, ages, replace = TRUE),
    "Sex" = sample(c("M", "F"), n, prob = p_sex, replace = TRUE))   
  return(initpop)
}


## Function 16. Initialize initial list of sites
#' @title Initialize list of sites
#' @description Initialize list of sites across the years of a simulation
#' @param list_sites a list of population for all initial sites of the simulation
#' @param ts length of simulation
#' @export
#' @return matrix of list sites
initlistsites <- function(list_sites, ts=200){
  Nts <- matrix(0, nrow=ts+1, ncol=length(list_sites))
  Nts[1,] <- sapply(list_sites, nrow)
  return(Nts)
}



